language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
    app: castlemock
  on:
    branch: master
    jdk: openjdk10

notifications:
  slack: $SLACK_KEY