language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "castlemock"
  local_dir: code/web/war/build/libs
  skip_cleanup: true
  upload-dir: package/war/latest
  on:
    branch: master
    jdk: oraclejdk8

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "castlemock"
  local_dir: code/web/war/build/libs
  skip_cleanup: true
  upload-dir: package/war/$TRAVIS_TAG
  on:
    tags: true
    jdk: oraclejdk8