language: java

jdk:
  - oraclejdk8

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  draft: true
  file: code/web/war/build/libs/castlemock-1.19-SNAPSHOT.war
  skip_cleanup: true
  tag_name: develop
  file_glob: true
  overwrite: true
  on:
    branch: develop