language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: bintray
  file: .bintray
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true
  on:
    branch: master
    jdk: openjdk10

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  draft: false
  file: code/web/war/build/libs/castlemock.war
  skip_cleanup: true
  name: "Castle Mock v" $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  on:
    branch: master
    tags: true
    jdk: openjdk10

deploy:
  provider: script
  script: bash docker-upgrade.sh $TRAVIS_TAG
  on:
    branch: master
    tags: true
    jdk: openjdk10